name: IndexNow Submission

on:
  push:
    branches:
      - main

jobs:
  submit-indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Submit URLs to IndexNow
        uses: c2c24/indexnow-action@v1.1.0
        with:
          domain: 'www.caritasem.com'
          key: 'a3863e049ced424ca04b179fb91c801c'
          keyLocation: 'https://www.caritasem.com/a3863e049ced424ca04b179fb91c801c.txt'
          sitemapLocation: 'https://www.caritasem.com/sitemap.xml'
